### PR TITLE
Fix #39 Unicode String indexing

### LINKED ISSUE #39: Unicode (Greek) Characters throw error
```
julia> printfmt("a {}", 2)
a 2
julia> printfmt("α {}", 2)
ERROR: Unmatched { in format expression.
 in find_next_entry_open(::String, ::Int64) at /home/raka/.julia/v0.5/Formatting/src/formatexpr.jl:92
 in Formatting.FormatExpr(::String) at /home/raka/.julia/v0.5/Formatting/src/formatexpr.jl:124
 in printfmt(::Base.TTY, ::String, ::Int64) at /home/raka/.julia/v0.5/Formatting/src/formatexpr.jl:162
 in printfmt(::String, ::Int64) at /home/raka/.julia/v0.5/Formatting/src/formatexpr.jl:163

```

### PR DESCRIPTION
**Pull request by jmkuhn**
Fixes #39.

### CODE REVIEW

File: src/formatexpr.jl [hunk 1]
```diff
@@ -87,15 +87,15 @@ end
 _raise_unmatched_lbrace() = error("Unmatched { in format expression.")
 
 function find_next_entry_open(s::AbstractString, si::Int)
-    slen = length(s)
+    slen = sizeof(s)
```
Comment (nalimilan) [inline src/formatexpr.jl]: This should probable be `endof(s)`. Same below.

File: src/formatexpr.jl [hunk 2]
```diff
@@ -104,15 +104,15 @@ function find_next_entry_open(s::AbstractString, si::Int)
 end
 
 function find_next_entry_close(s::AbstractString, si::Int)
-    slen = length(s)
+    slen = endof(s)
```
Comment (nalimilan) [inline src/formatexpr.jl]: Actually, `slen` isn't used here nor below, so it could even be removed. I also suspect the use of that variable in the function above is incorrect since `search` never returns an index beyond the last valid index, but that's an issue for another PR.

**Comment by kmsquire** [comment]
@jmkuhn pointed out elsewhere that these PRs have been sitting here for a long time.  It would be nice if the unneeded `slen` were removed, but that can happen in a separate PR.
